# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: Documentation for iTell
site_author: Lear Lab
theme:
  name: material
  features:
    # - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  # - toc.integrate
  font:
    text: Roboto
    code: Roboto Mono

  palette:
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

markdown_extensions:
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.superfences

nav:
  - Home: index.md
  - What is iTELL:
    - About: about/about.md
  - Development:
    - Starting the website: development/dependency.md
    - Adding textbook content: development/content.md
  - Data Schema:
    - User Identity: data/identity.md
    - Summaries: data/summary.md
    - Keystroke Logging: data/keystrokes.md
    - Focus Time: data/focus.md
    - Google Analytics: data/ga.md

